Story4/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('firstapp.urls')),
    path('storysatu/', include('storysatu.urls')),
    path('kegiatan/', include('app_story6.urls'))
]

app_story6/urls.py
from django.urls import path
from . import views

app_name = 'story6'

urlpatterns = [
    path('', views.tambahKegiatan, name='tambahKegiatan'),
    path('lihat/', views.lihatKegiatan, name='lihatKegiatan'),
    path('lihat/register/<int:ids>/', views.tambahPeserta, name='tambahPeserta'),
    path('lihat/<int:ids>/', views.hapusPeserta, name='hapusPeserta')
]

firstapp/urls.py
from django.urls import path

from . import views

app_name = 'firstapp'

urlpatterns = [
    path('', views.home, name='home'),
    path('about', views.about, name='about'),
    path('achievements', views.achievements, name='achievements'),
    path('time/<str:timezone>', views.time),
    path('schedule/', views.indexjadwal, name='indexjadwal'),
    path('inputSchedule', views.schedule, name='schedule'),
    path('viewSchedule/<int:pk>', views.viewSchedule, name='viewSchedule'),
    path('delete/<str:mataKuliah>', views.delete, name='delete')
]

storysatu/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('story1', views.story1, name='story1'),
]

app_story6/models.py
from django.db import models

# Create your models here.

class Kegiatan(models.Model):
    Nama_Kegiatan = models.CharField(max_length=50)
    def __str__(self):
        return self.nama

class Peserta(models.Model):
    Nama_Peserta = models.CharField(max_length=50)
    ikutKegiatan = models.ForeignKey(Kegiatan, on_delete=models.CASCADE, null=True, blank=True)

firstapp/models.py
from django.db import models

# Create your models here.

class Schedule(models.Model):
    mataKuliah = models.CharField(max_length=50)
    dosenPengajar = models.CharField(max_length=25)
    jumlahSKS = models.CharField(max_length=4)
    semesterTahun = models.CharField(max_length=20)
    ruang = models.CharField(max_length=10)
    deskripsi = models.CharField(max_length=100)

    def __str__(self):
        return self.mataKuliah

storysatu/models.py
from django.db import models

# Create your models here.

app_story6/forms.py
from django import forms
from .models import Kegiatan, Peserta

class KegiatanForm(forms.ModelForm):
    class Meta:
        model = Kegiatan
        fields = ['Nama_Kegiatan']

class PesertaForm(forms.ModelForm):
    class Meta:
        model = Peserta
        fields = ['Nama_Peserta']

firstapp/forms.py
from django import forms
from .models import Schedule

class ScheduleForm(forms.ModelForm):
    class Meta:
        model = Schedule
        fields = ['mataKuliah', 'dosenPengajar', 'jumlahSKS', 'semesterTahun', 'ruang', 'deskripsi']

app_story6/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Kegiatan, Peserta
from .forms import KegiatanForm, PesertaForm

# Create your views here.

def lihatKegiatan(request):
    kegiatan = Kegiatan.objects.all()
    peserta = Peserta.objects.all()
    return render(request, 'lihatKegiatan.html', {'kegiatan':kegiatan, 'peserta':peserta})


def tambahKegiatan(request):
    if request.method == "POST":
        form = KegiatanForm(request.POST)

        if form.is_valid():
            form.save()
            return redirect('story6:lihatKegiatan')

    else:
        form = KegiatanForm()

    return render(request, 'tambahKegiatan.html', {'form':form})

def tambahPeserta(request, ids):
    if request.method == "POST":
        form = PesertaForm(request.POST)

        if form.is_valid():
            peserta = Peserta(ikutKegiatan=Kegiatan.objects.get(id=ids), Nama_Peserta = form.data['Nama_Peserta'])
            peserta.save()
            return redirect('../../')
    
    else:
        form = PesertaForm()

    return render(request, 'tambahPeserta.html', {'form':form})

def hapusPeserta(request, ids):
    hapus_peserta = get_object_or_404(Peserta, id = ids)

    if request.method == "POST":
        hapus_peserta.delete()
        return redirect('../')

    return render(request, 'hapusPeserta.html', {'hapus_peserta':hapus_peserta})

firstapp/views.py
from django.shortcuts import render, redirect

# Create your views here.
from django.http import HttpResponse
import datetime
from .models import Schedule
from .forms import ScheduleForm



def home(request):
    return render(request,'landing-page.html')

def about(request):
    return render(request, 'index.html')

def achievements(request):
    return render(request, 'prestasi.html')

def time(request, timezone="0"):
    time = datetime.datetime.now() + datetime.timedelta(hours=int(timezone)+7)
    return render(request, 'time.html', {'time':time})

def indexjadwal(request):
    matkul = Schedule.objects.all()
    context = {
        'object' : matkul
    }
    return render(request, 'indexjadwal.html', context)


def schedule(request):
    if request.method == "POST":
        form = ScheduleForm(request.POST)

        if form.is_valid():
            form.save()
            return redirect('firstapp:indexjadwal')
    
    else:
        form = ScheduleForm()

    return render(request, 'jadwal.html', {'form':form})

def delete(request, mataKuliah):
    matKul = Schedule.objects.filter(mataKuliah = mataKuliah)
    matKul.delete()
    return redirect('firstapp:schedule')

def viewSchedule(request, pk):
    matkul = Schedule.objects.get(id=pk)
    return render(request, 'viewSchedule.html', {'x' : matkul})

storysatu/views.py
from django.shortcuts import render

# Create your views here.
from django.http import HttpResponse

def story1(request):
    return render(request, 'indexx.html')

app_story6/templates/hapusPeserta.html
{% extends 'base.html' %}
{% load static %}

{% block body %}
<div class="container">
    <h4> Apakah kamu yakin ingin menghapus {{ hapus_peserta.Nama_Peserta }}? </h4>
</div>

<form action="." method="POST">
    {% csrf_token %}
    <input class="btn btn-danger" type="submit" value="Hapus" />
    <a href="../" class="btn btn-primary">Cancel</a>
</form>
{% endblock %}

app_story6/templates/lihatKegiatan.html
{% extends 'base.html' %}
{% load static %}

{% block body %}
{% for x in kegiatan %}
<div class="container">
    <table class="table table-bordered">
        <tr>
            <td class="table-secondary" style="background-color: sandybrown;">{{ x.Nama_Kegiatan }}</td>
        </tr>
        <tr>
            {% for y in peserta %}
            {% if y.ikutKegiatan == x %}
            <tr>
                <td> {{ y.Nama_Peserta }} <a type="button" class="btn btn-outline-danger" href="{% url 'story6:hapusPeserta' y.id %}">Hapus</a></td>
            </tr>
            {% endif %}
            {% endfor %}
        </tr>
    </table>
</div>

<div class="container text-center">
    <a href="register/{{ x.id }}" class="text-white btn btn-primary mx-auto my-2 click">
        Register {{ x.namaKegiatan }}
    </a>
</div>
{% endfor %}

{% endblock %}

app_story6/templates/tambahKegiatan.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load static %}

{% block body %}
<form method="POST" style="display: flex; justify-content: center; align-items: center; flex-direction: column">
    {% csrf_token %}
    {{ form|crispy }}
  
    <h5>* = Wajib Diisi</h5>
    <input class="btn btn-primary" type="submit" value="Save" />
    <a type="button" class="btn btn-primary" href="lihat/"> Lihat Kegiatan</a>
    <a type="button" class="btn btn-success" href="../">Home</a>
  </form>

  
{% endblock %}

app_story6/templates/tambahPeserta.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load static %}

{% block body %}
<form method="POST" style="display: flex; justify-content: center; align-items: center; flex-direction: column">
  {% csrf_token %}
  {{ form|crispy }}

  <h5>* = Wajib Diisi</h5>
  <input class="btn btn-primary" type="submit" value="Save" />
  <a type="button" class="btn btn-danger" href="../../">Back</a>
</form>

{% endblock %}

firstapp/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" type="text/css" href="{% static 'CSS/maincss.css'%}">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <title>Document</title>
</head>
<body style="background-color: #95d5ff;">
    {% include 'includes/navbar.html' %}
    {% block body %} {% endblock %}
</body>
</html>

firstapp/templates/includes/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <a class="navbar-brand" href="#">Navbar</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
      <div class="navbar-nav">
        <a class="nav-item nav-link" href="./">Home <span class="sr-only">(current)</span></a>
        <a class="nav-item nav-link" href="./about">Tentang Saya</a>
        <a class="nav-item nav-link" href="#Organization">Pengalaman Organisasi</a>
        <a class="nav-item nav-link" href="./achievements">Prestasi & Sertifikat</a>
        <a class="nav-item nav-link" href="#Education">Riwayat Pendidikan</a>
        <a class="nav-item nav-link" href="./inputSchedule">Jadwal</a>
        <a class="nav-item nav-link" href="#Contacts">Kontak</a>
        <a class="nav-item nav-link" href="#Gallery">Galeri Foto</a>
        <a class="nav-item nav-link" href="./storysatu/story1">Story 1</a>
        <a class="nav-item nav-link" href="./kegiatan">Kegiatan</a>

      </div>
    </div>
</nav>

firstapp/templates/index.html
{% extends 'base.html' %}
{% load static %}

{% block body %}
      <div class="containerindex" style="background-color: #FFBF95;">
        <div class="image">
          <img src="{% static 'images/wibu galan.jpg'%}" class="img-fluid" alt="Responsive image">
        </div>
        <div class="para">
          <h3> Halo semua, nama saya</h3><br>
          <h1>IRHAM TRISNA ANANTO</h1> <br>
          <h5><p>Saya merupakan seorang mahasiswa semester 2 yang sedang berkuliah di Universitas Indonesia jurusan Sistem Informasi. Hobi saya menyanyi, mendengarkan lagu, dan ikut dalam kepanitiaan/organisasi. Motto hidup saya adalah lihatlah lebih dekat dan kau bisa menilai segalanya dengan lebih bijaksana. Jangan sungkan untuk mengontak saya. Semoga hari-hari kalian menjadi lebih menyenangkan!</p></h5>
        </div>
      </div>
{% endblock %}

firstapp/templates/indexjadwal.html
{% extends 'base.html' %}

{% block body %}
<h1>JADWAL KULIAH</h1>

<div class="table-responsive">

    <table class="table table-hover" style="padding-left: 10px; padding-right: 10px;">
        <thead>
            <tr>
                <th scope="col">Nama Mata Kuliah</th>
                <th scope="col">Dosen Pengajar</th>
                <th scope="col">Jumlah SKS</th>
                <th scope="col">Semester Tahun</th>
                <th scope="col">Ruang</th>
                <th scope="col">Deskripsi</th>
            </tr>
        </thead>
        
        <tbody>
            {% for x in object %}
                <tr class='clickable-row'>
                    <td><a href="{% url 'firstapp:viewSchedule' x.id %}">{{ x.mataKuliah }}</a></td>
                    <td>{{ x.dosenPengajar }}</td>
                    <td>{{ x.jumlahSKS }}</td>
                    <td>{{ x.semesterTahun }}</td>
                    <td>{{ x.ruang }}</td>
                    <td>{{ x.deskripsi|slice:":15" }}</td>
                </tr>
            {% endfor %}
        </tbody>

        
        
        

    </table>

    <form>
        <button type="submit" class="btn btn-outline-success btn-block" formaction="{% url 'firstapp:indexjadwal' %}">Add</button>
    </form>
    
</div>

{% endblock %}

firstapp/templates/jadwal.html
{% extends 'base.html' %}
{% load static %}

{% block body %}
<form action="" method="POST" style="display: flex; justify-content: center; align-items: center; flex-direction: column">
  {% csrf_token %}
  
  {{ form }}
  <button type="submit" class="btn btn-outline-success btn-block">Add</button>
</form>

{% endblock %}

firstapp/templates/landing-page.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'CSS/maincss.css'%}">
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <title>Document</title>
</head>
<body>
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-8">
                <div class="transparent-backg">
                    <img src="{% static 'images/Istana Merdeka.jpg'%}" width="100%" style="opacity: 0.6;" style="padding: 0px;">
                </div>
            </div>
            <div class="col-md-4" style="background-color: #95d5ff;">
                <center>
                <div class="image">
                    <img src="{% static 'images/Selfie Hnm1.jpg'%}" width="160px" height="180px" class="rounded-circle" style="margin-top: 2vh;">
                </div>
                <h2>Halo! Aku Irham</h2>
                <p style="margin-top: 2vh;">Seorang mahasiswa tahun pertama Fasilkom UI yang masih mencari makna hidup dan terus berbahagia serta berbagi kebahagiaan kepada sesama. Jika melihat video cover lagu saya di Instagram, mohon jangan request lagu karena kemungkinan tidak akan saya nyanyikan.</p>
                <a href="./about"><buttonreadmore class="btn btn-primary" type="submit">Read More</button></a>
                    
                <button type="button" class="btn btn-info btn-md" data-toggle="modal" data-target="#myModal">Mini Gallery</button>
                    <div id="myModal" class="modal fade" role="dialog">
                        <div class="modal-dialog">
                            <div class="modal-content">
                                <div class="modal-header">
                                    <h4 class="modal-title">Mini Galeri Foto</h4>
                                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                                </div>
                                <div class="modal-body">
                                    <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
                                        <ol class="carousel-indicators">
                                        <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
                                        <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
                                        <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
                                        </ol>
                                        <div class="carousel-inner">
                                            <div class="carousel-item active">
                                                <img class="d-block w-100" src="{% static 'images/YudaZalfa.jpg'%}" alt="Foto bersama Yuda dan Zalfa">
                                            </div>
                                            <div class="carousel-item">
                                                <img class="d-block w-100" src="{% static 'images/Buken.jpg'%}" alt="Foto XII Mipa 1">
                                            </div>
                                            <div class="carousel-item">
                                                <img class="d-block w-100" src="{% static 'images/GBN.jpg'%}" alt="Foto bersama GBN DKI Jakarta">
                                            </div>
                                        </div>
                                        <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
                                            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                                            <span class="sr-only">Previous</span>
                                        </a>
                                        <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
                                            <span class="carousel-control-next-icon" aria-hidden="true"></span>
                                            <span class="sr-only">Next</span>
                                        </a>
                                    </div>
                                </div>
                                <div class="modal-footer">
                                    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                                </div>
                            </div>
                        </div>
                    </div>
                </center>
            </div>   
        </div>
    </div>
</body>
</html>

firstapp/templates/prestasi.html
{% extends 'base.html' %}
{% load static %}

{% block body %}
      <br> <center> <h1> PRESTASI </h1> </center> <br>
      <div class="containerprestasi">
        <img src="{% static 'images/VG.jpg' %}" width="75%" alt="""> <br>
        <div class="table-responsive-sm">
            <table class="table table-borderless">
                <thead>
                    <tr>
                      <th scope="col">Nama Kegiatan</th>
                      <th scope="col">Tahun</th>
                      <th scope="col">Deskripsi Kegiatan</th>
                    </tr>
                </thead>
                  <tbody>
                    <tr>
                      <td>Gita Bahana Nusantara</td>
                      <td>2018</td>
                      <td>Gita Bahana Nusantara merupakan tim paduan suara nasional yang dibentuk oleh Kementerian Pendidikan dan Kebudayaan untuk mengisi acara kenegaraan Upacara Hari Ulang Tahun ke-73 Republik Indonesia di Istana Merdeka.</td>
                    </tr>
                    <tr>
                      <td>Lomba Paduan Suara Tingkat SMA se-DKI Jakarta</td>
                      <td>2017</td>
                      <td>Juara I lomba paduan suara tingkat SMA/SLTA se-DKI Jakarta. Lomba ini diselenggarakan oleh Dinas Pariwisata Provinsi DKI Jakarta yang diikuti oleh 14 SMA/SLTA se-DKI Jakarta.</td>
                    </tr>
                    <tr>
                      <td>Lomba Paduan Suara Tingkat SMA se-DKI Jakarta</td>
                      <td>2018</td>
                      <td>Juara III lomba paduan suara tingkat SMA/SLTA se-DKI Jakarta. Lomba ini diselenggarakan oleh Dinas Pariwisata Provinsi DKI Jakarta bersama dengan Kementerian Pendidikan dan Kebudayaan Republik Indonesia yang diikuti oleh 15 SMA/SLTA se-DKI Jakarta</td>
                    </tr>
                    <tr>
                        <td>Lomba Vocal Group UI Art War</td>
                        <td>2019</td>
                        <td>Juara III lomba vocal group pada perhelatan UI Art War ke-9 yang diikuti oleh 13 Fakultas di Universitas Indonesia</td>
                    </tr>
                  </tbody>
            </table>
          </div>
      </div>
{% endblock %}

firstapp/templates/time.html
{% extends 'base.html' %}

{% block body %}
<div style="margin-top: 30vh; margin-left: 15vw; color: blue; font-size: 24pt;">
    {{ time }}
</div>
{% endblock %}

firstapp/templates/viewSchedule.html
{% extends 'base.html' %}
{% load static %}


{% block body %}

    <div class="container-fluid table-responsive">
        <table class="table table-borderless">
            <thead>
                <tr>
                    <th class="col-md-auto" scope="col"></th>
                    <th class="col-md-auto" scope="col"></th>
                </tr>
            </thead>

            <tbody>
                <tr>
                    <th scope="row">Nama Mata Kuliah</th>
                    <td><p class="h4">{{ x.mataKuliah }}</p></td>
                </tr>

                <tr>
                    <th scope="row">Dosen Pengajar</th>
                    <td><p class="h4">{{ x.dosenPengajar}}</p></td>
                </tr>

                <tr>
                    <th scope="row">Jumlah SKS</th>
                    <td><p class="h4">{{ x.jumlahSKS }}</p></td>
                </tr>

                <tr>
                    <th scope="row">Semester Tahun</th>
                    <td><p class="lead">{{ x.semesterTahun }}</p></td>
                </tr>

                <tr>
                    <th scope="row">Ruang</th>
                    <td><p class="h4">{{ x.ruang }}</p></td>
                </tr>

                <tr>
                    <th scope="row">Deskripsi</th>
                    <td><p class="h4">{{ x.deskripsi }}</p></td>
                </tr>
            </tbody>
        </table>
    </div>
        
    <form>
        <button type="submit" class="btn btn-outline-danger btn-block" formaction="{% url 'firstapp:delete' x.mataKuliah %}">Delete</button>
    </form>

{% endblock %}

storysatu/templates/indexx.html
{% load static %}
<html>
    <head>
        <link rel="stylesheet" type="text/css" href="{% static 'CSS/style.css'%}">
        <title> Story 1  PPW </title>
    </head>
    <body>
        <div class="header">
            <h1>Irham Trisna Ananto</h1>
        </div>
        <br>
        <img src="{% static 'images/yudamaba.jpg'%}" alt="Foto dengan Yuda" width="200" height="266">  
        <p><b><h1> Halo, aku Irham! </h1></b></p>

        <br>
        <p><h2> Nama </h2></p>
        <p><h4><t> Irham Trisna Ananto </t></h4></p>
        <p><h2> NPM </h2></p>
        <p><h4><t> 1906353870 </t></h4></p>
        <p><h2> Angkatan </h2></p>
        <p><h4><t> Maung 2019 </t></h4></p>
        <p><h2> NPM </h2></p>
        <p><h4><t> 1906353870 </t></h4></p>
        <p><h2> Hobi </h2></p>
        <p><h4><t> Menyanyi, nonton Youtube, mengobrol </t></h4></p>
        <p><h2> Deskripsi </h2></p>
        <p><h4><t> Nama saya Irham Trisna Ananto, panggil saja Irham. Saya merupakan mahasiswa S1 Sistem Informasi Reguler di Fasilkom UI </t></h4></p>
        
        <p><h2> Riwayat Pendidikan </h2></p>
        <br>
        <table>
            <tr>
                <th> Nama Institusi </th>
                <th> Tahun </th>
            </tr>
            <tr>
                <td> SD Negeri Pekayon 18 Pagi </td>
                <td> 2007 - 2013 </td>
            </tr>
            <tr>
                <td> SMP Negeri 91 Jakarta </td>
                <td> 2013 - 2016 </td>
            </tr>
            <tr>
                <td> SMA Negeri 39 Jakarta </td>
                <td> 2016 - 2019 </td>
            </tr>
            <tr>
                <td> Universitas Indonesia </td>
                <td> 2019 - </td>
            </tr>
        </table>
        <br>
        <h4> Yuk kenalan dengan saya! </h4>
        <a href="http://www.instagram.com/irhamtrisna">
            <img src="{% static 'images/instagram1.png'%}" alt="Instagram Logo" width="30" height="30">
        </a>
        <a href="https://www.linkedin.com/in/irhamtrisna-ananto/">
            <img src="{% static 'images/linkedin.png'%}" alt="LinkedIn Logo" width="30" height="30">
        </a>
    </body>
</html>